src/feeds/urls.py
from django.urls import path
from .internal_feeds import CategoryFeed

from . import views

app_name = "feeds"

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("contact", views.contact, name="contact"),
    path("curated", views.curated, name="curated"),
    path("all", views.all, name="all"),
    path("<int:feed_item_id>/", views.detail, name="detail"),
    path("feed", views.list_feeds, name="list_feeds"),
    path("feed/<int:feed_id>/all", views.feed_all, name="feed_all"),
    path("feed/<int:feed_id>/curated", views.feed_curated, name="feed_curated"),
    path("feed/category/<int:category_id>/all", views.feed_category_all, name="feed_category_all"),
    path("feed/category/<int:category_id>/curated", views.feed_category_curated, name="feed_category_curated"),
    path("api/like/<int:feed_item_id>/", views.api_like, name="api_like"),
    path("api/unlike/<int:feed_item_id>/", views.api_unlike, name="api_unlike"),
    path('rss/<slug:slug>/<str:item_type>/', CategoryFeed(), name='category_rss_feed'),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('entries/', include('entries.urls')),
    path('', include('feeds.urls')),
    path('admin/', admin.site.urls),
]

src/feeds/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify

# This is the model to describe how the rss/atom xml for a specific feed maps to Item
class ItemFeedMap(models.Model):
    item_feed_map_name = models.CharField(max_length=200)
    items = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    link = models.CharField(max_length=200)
    item_id = models.CharField(max_length=200)
    published = models.CharField(max_length=200)
    updated = models.CharField(max_length=200)
    content = models.CharField(max_length=200)
    summary = models.CharField(max_length=200)
    image_url = models.CharField(max_length=200)
    audio_url = models.CharField(max_length=200, default='')

    def __str__(self):
        return self.item_feed_map_name

class FeedCategory(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)  # optional description field
    slug = models.SlugField(null=False, blank=True, unique=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)
    
    @property
    def all_feed_url(self):
        """
        Returns the hardcoded URL for the 'all' RSS feed for this category.
        """
        return f'/rss/{self.slug}/all/'

    @property
    def curated_feed_url(self):
        """
        Returns the hardcoded URL for the 'curated' RSS feed for this category.
        """
        return f'/rss/{self.slug}/curated/'


# This is the model for the feed, e.g. for https://konstellationen.org/atom.xml
class Feed(models.Model):
    name = models.CharField(max_length=200)
    url = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    item_feed_map = models.ForeignKey(ItemFeedMap, on_delete=models.CASCADE)
    category = models.ForeignKey(FeedCategory, on_delete=models.SET_NULL, null=True, blank=True)
    political_affiliation = models.CharField(max_length=200, blank=True, null=True)
    publisher = models.CharField(max_length=200, blank=True, null=True)
    website_url = models.URLField(max_length=200, null=True, blank=True)
    mastodon_account_url = models.URLField(max_length=200, null=True, blank=True)
    slug = models.SlugField(null=False, blank=True, unique=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

# This describes a generic rss/atom feed item
class Item(models.Model):
    feed = models.ForeignKey(Feed, on_delete=models.CASCADE)
    # These are things related to the moderation on this site
    date_processed = models.DateTimeField("date processed", null=True)
    show_item = models.BooleanField(default=False)
    imported = models.DateTimeField("date imported", null=True)

    # The following fields are fields taken from the rss/atom feed
    title = models.CharField(max_length=200)
    # An external link, to the news article, blog post, podcast, etc.
    link = models.CharField(max_length=200)
    item_id = models.CharField(max_length=200)
    published = models.DateTimeField("date published", null=True, blank=True)
    updated = models.DateTimeField("date updated", null=True, blank=True)
    content = models.TextField(blank=True)
    summary = models.TextField(blank=True)
    image_url = models.CharField(max_length=200, blank=True)
    audio_url = models.CharField(max_length=200, blank=True)
    
    def get_absolute_url(self):
        # Assuming you have a view named 'item_detail' that takes the item's ID as an argument
        return reverse('item_detail', args=[str(self.id)])

    def __str__(self):
        return "{} - {}".format(self.feed, self.title)

src/feeds/views.py
from django.urls import reverse
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.db.models import Prefetch
from django.conf import settings

from datetime import timedelta

from .models import Item
from .models import Feed
from .models import FeedCategory


def index(request):
    now = timezone.now()

    # Identify the FeedCategory instances for news, blog, and podcast
    news_category_name = settings.NEWS_CATEGORY_NAME
    blog_category_name = settings.BLOG_CATEGORY_NAME
    podcast_category_name = settings.PODCAST_CATEGORY_NAME
    event_category_name = settings.EVENT_CATEGORY_NAME

    latest_news_category_length = settings.LATEST_NEWS_CATEGORY_LENGTH
    latest_blog_category_length = settings.LATEST_BLOG_CATEGORY_LENGTH
    latest_podcast_category_length = settings.LATEST_PODCAST_CATEGORY_LENGTH
    latest_event_category_length = settings.LATEST_EVENT_CATEGORY_LENGTH

    news_category = FeedCategory.objects.get(name=news_category_name)
    blog_category = FeedCategory.objects.get(name=blog_category_name)
    podcast_category = FeedCategory.objects.get(name=podcast_category_name)
    event_category = FeedCategory.objects.get(name=event_category_name)

    # Fetch news articles
    news_articles = Item.objects.filter(show_item=True, feed__category=news_category).order_by("-published")[:latest_news_category_length]

    # Fetch blog posts
    blog_posts = Item.objects.filter(show_item=True, feed__category=blog_category).order_by("-published")[:latest_blog_category_length]

    # Fetch podcasts
    podcasts = Item.objects.filter(show_item=True, feed__category=podcast_category).order_by("-published")[:latest_podcast_category_length]

    # Fetch events
    events = Item.objects.filter(show_item=True, feed__category=event_category, published__gte=now).order_by("published")[:latest_event_category_length]

    context = {
        "chosen_news": news_articles,
        "chosen_blog_posts": blog_posts,
        "chosen_podcasts": podcasts,
        "chosen_events": events,
        "news_category_id": news_category.pk,
        "blog_category_id": blog_category.pk,
        "podcast_category_id": podcast_category.pk,
        "event_category_id": event_category.pk
    }

    return render(request, "index.html", context)

def about(request):
    return render(request, "about.html", {})

def contact(request):
    return render(request, "contact.html", {})

def all(request):
    item_list = Item.objects.all().order_by("-published")
    # 50 per page
    paginator = Paginator(item_list, 50)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "feed/index.html", {
        "feed_type": "all",
        "page_obj": page_obj,
    })

def curated(request):
    item_list = Item.objects.filter(show_item=True).order_by("-published")
    # 50 per page
    paginator = Paginator(item_list, 50)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "feed/index.html", {
        "feed_type": "curated",
        "page_obj": page_obj,
    })

def feed_all(request, feed_id):
    # Attempt to get the feed for the ID and 404 if we can't find it.
    feed = get_object_or_404(Feed, pk=feed_id)

    # Retrieve feed items for a specific feed, ordered by the published date with the most recent ones first.
    items = Item.objects.filter(feed_id=feed_id).order_by("-published")

    # Paginate the feed's items with 50 items per page.
    paginator = Paginator(items, 50)

    # Use the URL query parameter "page" to select which page to show.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(request, "feed/index.html", {
        "feed_type": "all",
        "feed": feed,
        "page_obj": page_obj
    })

def feed_curated(request, feed_id):
    # Attempt to get the feed for the ID and 404 if we can't find it.
    feed = get_object_or_404(Feed, pk=feed_id)

    # Retrieve feed items for a specific feed, ordered by the published date with the most recent ones first.
    # Also filter the items based on "show_item" which determines if it's curated or not.
    items = Item.objects.filter(feed_id=feed_id, show_item=True).order_by("-published")

    # Paginate the feed's items with 50 items per page.
    paginator = Paginator(items, 50)

    # Use the URL query parameter "page" to select which page to show.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(request, "feed/index.html", {
        "feed_type": "curated",
        "feed": feed,
        "page_obj": page_obj
    })

def feed_category_all(request, category_id):
    # Attempt to get the category for the ID and 404 if we can't find it.
    category = get_object_or_404(FeedCategory, pk=category_id)
    all_feed_url = category.all_feed_url

    # Retrieve all items for a specific category ordered by the published date with the most recent ones first.
    items = Item.objects.filter(feed__category=category).order_by("-published")

    # Paginate the feed's items with 50 items per page.
    paginator = Paginator(items, 50)

    # Use the URL query parameter "page" to select which page to show.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    # return render(request, "cateory/index.html", {
    return render(request, "feed/index.html", {
        "feed_type": "all",
        "category": category,
        "page_obj": page_obj,
        "all_feed_url": all_feed_url
    })

def feed_category_curated(request, category_id):
    # Attempt to get the category for the ID and 404 if we can't find it.
    category = get_object_or_404(FeedCategory, pk=category_id)
    curated_feed_url = category.curated_feed_url

    # Retrieve all items for a specific category ordered by the published date with the most recent ones first.
    items = Item.objects.filter(feed__category=category, show_item=True).order_by("-published")

    # Paginate the feed's items with 50 items per page.
    paginator = Paginator(items, 50)

    # Use the URL query parameter "page" to select which page to show.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    # return render(request, "category/index.html", {
    return render(request, "feed/index.html", {
        "feed_type": "curated",
        "category": category,
        "page_obj": page_obj,
        "curated_feed_url": curated_feed_url
    })

def detail(request, feed_item_id):
    item = get_object_or_404(Item, pk=feed_item_id)
    return render(request, "feed/item.html", {"item": item})

def list_feeds(request):
    # Order by the name of the category
    categories = FeedCategory.objects.prefetch_related(
        Prefetch(
            'feed_set', 
            queryset=Feed.objects.all().order_by('name')
        )
    ).order_by('name')
    return render(request, "feeds/index.html", {"categories": categories})


@csrf_exempt
def api_like(request, feed_item_id):
    if request.method != "POST":
        return JsonResponse({'success': False,'message':'Method not allowed'}, status=405)

    if not request.user.is_authenticated:
        return JsonResponse({'success': False,'message':'Not logged in'}, status=401)

    try:
        item = Item.objects.get(pk=feed_item_id)
        print("item")
        print(item)
        item.show_item = True
        item.date_processed = timezone.now()
        item.save()

        return JsonResponse({'success': True,'message':'Like successful'})

    except Item.DoesNotExist as e:
        return JsonResponse({'success': False,'message':'Item does not exist'}, status=404)

    except Exception as e:
        print("e")
        print(e)
        return JsonResponse({'success': False,'message':'Unknown error occured when liking'}, status=500)


@csrf_exempt
def api_unlike(request, feed_item_id):
    if request.method != "POST":
        return JsonResponse({'success': False,'message':'Method not allowed'}, status=405)

    if not request.user.is_authenticated:
        return JsonResponse({'success': False,'message':'Not logged in'}, status=401)

    try:
        item = Item.objects.get(pk=feed_item_id)
        print("item")
        print(item)
        item.show_item = False
        item.date_processed = timezone.now()
        item.save()

        return JsonResponse({'success': True,'message':'Unlike successful'})

    except Item.DoesNotExist as e:
        return JsonResponse({'success': False,'message':'Item does not exist'}, status=404)

    except Exception as e:
        print("e")
        print(e)
        return JsonResponse({'success': False,'message':'Unknown error occured when unliking'}, status=500)

src/feeds/templates/feed/_item.html
{% load humanize %}
<li class="item flex flex-row justify-start items-center w-full" data-key="{{ item.item_id }}">
    <div class="flex-none w-9 flex items-center justify-center">
        <a target="_blank" rel="noopener" referrerpolicy="origin" title="{{ item.title }}" class="dott w-2 h-2 rounded-full cursor-default" href="{{ item.link }}"></a>
    </div>
    <div class="flex-1 flex flex-col gap-1 w-full" style="min-width: 0;">
        <div class="flex flex-row justify-self-start items-center gap-2 text-sm"><time class="font-semibold">{{ item.published|naturaltime }}</time><a href="{% url 'feeds:feed_curated' item.feed_id %}" class="no-underline hover:underline font-light ">{{ item.feed.name }}</a></div>
        <a target="_blank" rel="noopener" referrerpolicy="origin" title="{{ item.title }}" class="no-underline hover:underline font-bold leading-tight line-clamp-3 md:line-clamp-2" href="{{ item.link }}">
            {{ item.title }}
        </a>
        {% if user.is_authenticated %}
            <div class="meta flex flex-row items-center justify-between pt-2 mr-8 md:justify-start">
                {% if item.show_item %}
                    <button class="flex flex-row items-center justify-start gap-1 text-semibold text-sm cursor-pointer" data-button-action="unlike" data-item_id="{{ item.id }}">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                        </svg>
                        <span class="text-red-700 font-bold">Avgilla</span>
                    </button>
                {% else %}
                    <button class="flex flex-row items-center justify-start gap-1 text-semibold text-sm cursor-pointer" data-button-action="like" data-item_id="{{ item.id }}">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
                        </svg>
                        <span class="text-green-700 font-bold">Gilla</span>
                    </button>
                {% endif %}

                <div class="flex items-center justify-center md:pl-8">
                    <a href="{% url 'admin:feeds_item_change' item.id %}" class="flex flex-row items-center justify-center gap-1 text-semibold text-sm cursor-pointer">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
                        </svg>
                        <span class="font-bold">Redigera</span>
                    </a>
                </div>
            </div>
        {% endif %}
    </div>
</li>

src/feeds/templates/feed/index.html
{% extends "base.html" %}

{% block content %}

<ul class="flex flex-col gap-6 pb-6 border-b">
	{% if feed.name %}
	<li class="flex flex-col gap-3 px-4 pt-6 md:px-0">
		<h1 class="text-2xl font-extrabold leading-none">{{ feed.name }}</h1>
		<p>
			{% if feed.description %}
				{{ feed.description }}
			{% endif %}
		</p>
		<p class="m-0 text-xs leading-relaxed">
		{% if feed.political_affiliation %}
			Politisk tillhörighet: {{ feed.political_affiliation }}<br/>
		{% endif %}
		{% if feed.publisher %}
			Utgivare: {{ feed.publisher }}<br/>
		{% endif %}
		<p class="m-0 text-xs leading-relaxed">
		{% if feed.website_url %}
			Hemsida: <a href="{{ feed.website_url }}" alt="Länk till hemsidan för {{ feed.name }}" target="_blank">{{ feed.website_url }}</a><br/>
		 {% endif %}
		Flöde: <a href="{{ feed.url }}" target="_blank">{{ feed.url }}</a><br/>
		{% if feed.mastodon_account_url %}
			Mastodonkonto: <a href="{{ feed.mastodon_account_url }}" alt="Länk till Mastodon-kontot för {{ feed.name }}" target="_blank">
				{{ feed.mastodon_account_url }}
			</a>
		 </p>
	{% endif %}
	</li>
	{% elif category.name %}
	<li class="flex flex-row items-center justify-between px-4 pt-6 md:px-0">
		<div class="flex flex-col gap-3">
			<h1 class="text-2xl font-extrabold leading-none">{{ category.name }}</h1>
			<p class="m-0 text-sm">{{ category.description }}</p>
		</div>
		<!-- RSS feed link -->
		{% if all_feed_url %}
			{% include '_rss_button.html' with feed_url=all_feed_url %}
		{% elif curated_feed_url %}
			{% include '_rss_button.html' with feed_url=curated_feed_url %}
		{% endif %}
	</li>
	{% endif %}
	<li class="sticky top-0 flex flex-row items-center justify-start py-3 border-t border-b md:pr-0 bg-omni-white dark:bg-black">
		<div class="flex justify-center w-9">
 			{% if feed_type == 'curated' %}
  			<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
				<path stroke-linecap="round" stroke-linejoin="round" d="M2.25 18L9 11.25l4.306 4.307a11.95 11.95 0 015.814-5.519l2.74-1.22m0 0l-5.94-2.28m5.94 2.28l-2.28 5.941" />
  			</svg>
 			{% else  %}
 			<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
   				<path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5m-9-6h.008v.008H12v-.008zM12 15h.008v.008H12V15zm0 2.25h.008v.008H12v-.008zM9.75 15h.008v.008H9.75V15zm0 2.25h.008v.008H9.75v-.008zM7.5 15h.008v.008H7.5V15zm0 2.25h.008v.008H7.5v-.008zm6.75-4.5h.008v.008h-.008v-.008zm0 2.25h.008v.008h-.008V15zm0 2.25h.008v.008h-.008v-.008zm2.25-4.5h.008v.008H16.5v-.008zm0 2.25h.008v.008H16.5V15z" />
 			</svg>
 			{% endif %}
		</div>
		<h3 class="flex flex-row items-center gap-3 text-base font-light grow">
 			{% if feed_type == 'all' %}
 				Alla
 			{% elif feed_type == 'curated' %}
 				Utvalda
 			{% else %}
 				{{ feed_type|capfirst }}
 			{% endif %}
 			{% if feed %} artiklar från {{ feed.name }}
			{% elif category %} inlägg från {{ category.name }}
 			{% else %} artiklar
 			{% endif %}
		</h3>
		<div class="flex flex-row gap-3 mr-2 text-sm justify-self-end">
			{% if feed %}
 				<a class="{% if feed_type == 'curated' %}text-omni-red{% endif %} no-underline hover:underline" href="{% url 'feeds:feed_curated' feed.id %}">Utvalda</a>
 				<a class="{% if feed_type == 'all' %}text-omni-red{% endif %} no-underline hover:underline" href="{% url 'feeds:feed_all' feed.id %}">Alla</a>
			{% elif category %}
			<a class="{% if feed_type == 'curated' %}text-omni-red{% endif %} no-underline hover:underline" href="{% url 'feeds:feed_category_curated' category.id %}">Utvalda</a>
			<a class="{% if feed_type == 'all' %}text-omni-red{% endif %} no-underline hover:underline" href="{% url 'feeds:feed_category_all' category.id %}">Alla</a>
			{% else %}
 				<a class="{% if feed_type == 'curated' %}text-omni-red{% endif %} no-underline hover:underline" href="{% url 'feeds:curated' %}">Utvalda</a>
 				<a class="{% if feed_type == 'all' %}text-omni-red{% endif %} no-underline hover:underline" href="{% url 'feeds:all' %}">Alla</a>
			{% endif %}
		</div>
	</li>
	{% for item in page_obj %}
		{% include "feed/_item.html" with item=item %}
	{% endfor %}
</ul>

<div class="px-4 my-6 pagination md:px-0">
	<span class="flex flex-row items-center justify-start gap-3 text-sm step-links">
		{% if page_obj.has_previous %}
			<a href="?page=1">Första</a>
			<a href="?page={{ page_obj.previous_page_number }}">Föregående</a>
		{% endif %}

		<span class="current">
			Sida {{ page_obj.number }} av {{ page_obj.paginator.num_pages }}.
		</span>

		{% if page_obj.has_next %}
			<a href="?page={{ page_obj.next_page_number }}">Nästa</a>
			<a href="?page={{ page_obj.paginator.num_pages }}">Sista</a>
		{% endif %}
	</span>
</div>
{% endblock %}

src/feeds/templates/feed/item.html
{% extends "base.html" %} {% block content %}
<h1>{{ item.title }}</h1>
<ul>
  <li>{{ item.link }}</li>
  <li>{{ item.published }}</li>
  <li>{{ item.summary }}</li>
</ul>
{% endblock %}